version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "14:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 3
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "14:15"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 3
